{
 "title": "Ecobee VM",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "period",
    "label": "Usage Period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "temperature{sensor=\"outdoor\"}"
    }
   ]
  },
  {
   "title": "Inside Temperature",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name) (sensor_temperature{name=\"EcobeeTherm: Kitchen\"})"
    }
   ]
  },
  {
   "title": "Today's Rain",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rain_in{period=\"daily\"}"
    }
   ]
  },
  {
   "title": "Inside Humidity",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg by (name) (humidity)" }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (name) (solar_radiation)"
    }
   ]
  },
  {
   "title": "Motion & Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "avg by (name) ((thermostat_cool_1 * 1) + (thermostat_cool_2 * 2) + (thermostat_heat_1 * 3) + (thermostat_heat_2 * 4) + (thermostat_aux_heat_1 * 5) + 10)",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg by (name) (sensor_occupancy)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (sensor_temperature) > 0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "temperature{sensor!~\"outdoor|dewpoint|feelsLike|1\"} > 0",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Outside Temps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "temperature{sensor!~\"indoor|[2-58]\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "none", "label": "inches" }
   ],
   "targets": [
    {
     "expr": "rain_in{period=\"daily\"}",
     "legendFormat": "Today's Rain"
    },
    {
     "expr": "rain_in{period=\"monthly\"}",
     "legendFormat": "Monthly Rain"
    },
    {
     "expr": "delta(rain_in{period=\"monthly\"}[15m]) * 4",
     "legendFormat": "Hourly Rain Rate (15m avg)"
    }
   ]
  },
  {
   "title": "Runtime (30 day)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = thermostat_heat_1,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Heat 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_heat_2,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Heat 2"
    },
    {
     "expr": "WITH (\n    metric = thermostat_aux_heat_1,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Aux"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_1,\n)\nsum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Cool 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_2,\n)\nsum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Cool 2"
    },
    {
     "expr": "sum(avg_over_time(temperature{sensor=\"outdoor\"}[1d]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = thermostat_heat_1,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Heat 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_heat_2,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Heat 2"
    },
    {
     "expr": "WITH (\n    metric = thermostat_aux_heat_1,\n)\n-sum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Aux"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_1,\n)\nsum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Cool 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_2,\n)\nsum by (name) (sum_over_time(metric[$period]))",
     "legendFormat": "Cool 2"
    },
    {
     "expr": "sum(avg_over_time(temperature{sensor=\"outdoor\"}[1d]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Runtime (30d) 1y ago",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "WITH (\n    metric = thermostat_heat_1,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Heat 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_heat_2,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Heat 2"
    },
    {
     "expr": "WITH (\n    metric = thermostat_aux_heat_1,\n)\n-sum_over_time(metric[$period])",
     "legendFormat": "Aux"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_1,\n)\nsum_over_time(metric[$period])",
     "legendFormat": "Cool 1"
    },
    {
     "expr": "WITH (\n    metric = thermostat_cool_2,\n)\nsum_over_time(metric[$period])",
     "legendFormat": "Cool 2"
    },
    {
     "expr": "sum(avg_over_time(temperature{sensor=\"outdoor\"}[1d]))",
     "legendFormat": "Weather"
    }
   ]
  },
  {
   "title": "Barometer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "expr": "barometer{type=\"relative\"} * 33.86388666666671",
     "legendFormat": "{{deviceName}}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "humidity", "legendFormat": "{{sensor}}" },
    { "expr": "sensor_humidity", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Wind Speed & Gusts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "expr": "max_over_time(wind_speed_mph{type=\"gusts\"}[1m])",
     "legendFormat": "GUSTS {{name}}"
    },
    {
     "expr": "max_over_time(wind_speed_mph{type=\"sustained\"}[1m])",
     "legendFormat": "SUSTAINED {{name}}"
    }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    { "expr": "solar_radiation", "legendFormat": "Solar Radiation" },
    { "expr": "ultraviolet", "legendFormat": "Ultraviolet {{name}}" }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
   "yaxes": [
    {
     "format": "degree",
     "label": "    N         E          S        W        N"
    }
   ],
   "targets": [
    { "expr": "wind_dir", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "Setpoints and Average Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (name) (sensor_temperature{name=\"EcobeeTherm: Kitchen\"})",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "avg by (name) (thermostat_cooling_setpoint)",
     "legendFormat": "Cooling Setpoint"
    },
    {
     "expr": "avg by (name) (thermostat_heating_setpoint)",
     "legendFormat": "Heating Setpoint"
    }
   ]
  }
 ]
}